# Introduction to Numpy arrays

In [1]:
import numpy as np

### One dimensional arrays
* select the first item using `arr.item(0)` or `arr[0]`
* `.item()` returns a copy of the element.
* Using `[]` accesses the element directly.
* Try looking at the types of both!

In [2]:
#:
a = np.array([1,2,3,4,5,6])

In [3]:
elt_copy = a.item(0)
print(elt_copy)
print(type(elt_copy))

1
<class 'int'>


In [4]:
elt_direct = a[0]
print(elt_direct)
print(type(elt_direct))

1
<class 'numpy.int64'>


### Change the third element of an array to `2018` via:
* `a[2] = 2019`

In [5]:
a[2] = 2019
a

array([   1,    2, 2019,    4,    5,    6])

### Comparisons return boolean arrays
* Each element of the boolean array is True/False if the comparison is True/False for the corresponding element in the original array.

In [6]:
a = np.array([1,2,3,4,5])
b = np.array([2,3,4,4,2])

In [7]:
print(a)
print(a > 2)

[1 2 3 4 5]
[False False  True  True  True]


In [8]:
print(a)
print(b)
print(a < b)

[1 2 3 4 5]
[2 3 4 4 2]
[ True  True  True False False]


### Change the elements of an array that correspond to `True` in a boolean array.
* Set every element of `a` that is greater than 2 equal to `2018`.
* Set every even element of `b` to zero.

In [9]:
a[a > 2] = 2019

In [10]:
a > 2

array([False, False,  True,  True,  True], dtype=bool)

In [11]:
a

array([   1,    2, 2019, 2019, 2019])

In [12]:
print(b)
print(b % 2 == 0)

[2 3 4 4 2]
[ True False  True  True  True]


In [13]:
b[b % 2 == 0] = 0

In [14]:
b

array([0, 3, 0, 0, 0])

### Multi-dimensional arrays
* define them using nested lists
* see the shape using `.shape`
* change shape/dimension using `.reshape(shape)`

### Creating 2-dimensional arrays (matrices)
* Example, black-and-white images are 2-dimensional arrays of pixels, where each element is an intensity between 0 and 256 (black is 0, white is 256).

In [15]:
a2 = np.array([[1,2,3],[2,3,4],[3,4,5],[4,5,6]])

In [16]:
a2

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [17]:
a2.shape

(4, 3)

In [19]:
a2.reshape(3,4)

array([[1, 2, 3, 2],
       [3, 4, 3, 4],
       [5, 4, 5, 6]])

In [20]:
a2.reshape(a2.size)

array([1, 2, 3, 2, 3, 4, 3, 4, 5, 4, 5, 6])

### Selecting rows and columns
* `a[i,j]` selects the element in the ith row and jth column (0-indexed!)
* `a[:,j]` selects the jth column.
* `a[i,:]` selects the ith column.

In [21]:
a2

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [22]:
a2[0,2]

3

In [23]:
a2[:,2]

array([3, 4, 5, 6])

In [24]:
a2[2,:]

array([3, 4, 5])

### Change elements using boolean arrays

In [25]:
a2[a2 % 2 == 0] = 0

In [26]:
a2

array([[1, 0, 3],
       [0, 3, 0],
       [3, 0, 5],
       [0, 5, 0]])

### 3 dimensional arrays
* Example, color pictures are 3 dimensional arrays: a triplet of 2D arrays (one for red intensities, one for green intensities, one for blue intensities).

In [27]:
a3 = np.array([
    [[1,2],[2,3],[3,4]],
    [[1,2],[2,3],[3,4]],
    [[1,2],[2,3],[3,4]]
])

In [28]:
a3

array([[[1, 2],
        [2, 3],
        [3, 4]],

       [[1, 2],
        [2, 3],
        [3, 4]],

       [[1, 2],
        [2, 3],
        [3, 4]]])

In [29]:
a3.shape

(3, 3, 2)

In [30]:
a3.reshape(a3.size)

array([1, 2, 2, 3, 3, 4, 1, 2, 2, 3, 3, 4, 1, 2, 2, 3, 3, 4])

In [31]:
a3[0,:,:]

array([[1, 2],
       [2, 3],
       [3, 4]])

In [32]:
a3[:,0,:]

array([[1, 2],
       [1, 2],
       [1, 2]])

In [33]:
a3[:,:,0]

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [ ]:
# EXCERCISE:
# 1. create a 100x100 matrix of numbers with uniformly distributed 
# elements 
# 2. calculate the mean of each column
# 3. calculate the total mean
#
# 3. how do we create a 100x100 matrix of numbers with a normal 
# distribution and mean=100 ?
# 4. calculate the mean to check if our approximation is good!



In [39]:
matrix = np.random.uniform(0,1,(10,10))

In [40]:
matrix

array([[ 0.58858173,  0.04200733,  0.72718259,  0.14501678,  0.76579718,
         0.7360703 ,  0.30827889,  0.07714457,  0.92031716,  0.52319744],
       [ 0.84155892,  0.54449036,  0.95132691,  0.18071884,  0.38819871,
         0.04991468,  0.82540448,  0.71774156,  0.75831801,  0.86191428],
       [ 0.32844692,  0.23311877,  0.44236559,  0.63477333,  0.09870117,
         0.87815447,  0.88743674,  0.37885868,  0.09213663,  0.52614167],
       [ 0.83809602,  0.92745808,  0.94866213,  0.47769414,  0.47952999,
         0.52212983,  0.07807024,  0.57279313,  0.90570386,  0.93258599],
       [ 0.09637731,  0.25040446,  0.22360761,  0.23913362,  0.56493887,
         0.74763036,  0.11819317,  0.6803421 ,  0.18412197,  0.71050996],
       [ 0.4580614 ,  0.43510856,  0.04469401,  0.85445848,  0.37683003,
         0.74648844,  0.81319124,  0.28120812,  0.6110259 ,  0.84931327],
       [ 0.94171694,  0.58195755,  0.4132323 ,  0.85199831,  0.17275074,
         0.92891904,  0.03752866,  0.27182216