# Introduction to Numpy arrays

In [33]:
import numpy as np

### One dimensional arrays
* select the first item using `arr.item(0)` or `arr[0]`
* `.item()` returns a copy of the element.
* Using `[]` accesses the element directly.
* Try looking at the types of both!

In [34]:
#:
a = np.array([1,2,3,4,5,6])

In [36]:
elt_copy = a.item(0)
print(elt_copy)
print(type(elt_copy))

1
<class 'int'>
[1 2 3 4 5 6]


In [39]:
elt_direct = a[0]
print(elt_direct)
print(type(elt_direct))

1
<class 'numpy.int64'>
[1 2 3 4 5 6]


### Change the third element of an array to `2018` via:
* `a[2] = 2018`

In [5]:
a[2] = 2018
a

array([   1,    2, 2018,    4,    5,    6])

### Comparisons return boolean arrays
* Each element of the boolean array is True/False if the comparison is True/False for the corresponding element in the original array.

In [40]:
a = np.array([1,2,3,4,5])
b = np.array([2,3,4,4,2])

In [41]:
print(a)
print(a > 2)

[1 2 3 4 5]
[False False  True  True  True]


In [42]:
print(a)
print(b)
print(a < b)

[1 2 3 4 5]
[2 3 4 4 2]
[ True  True  True False False]


### Change the elements of an array that correspond to `True` in a boolean array.
* Set every element of `a` that is greater than 2 equal to `2018`.
* Set every even element of `b` to zero.

In [43]:
a[a > 2] = 2018

In [44]:
a

array([   1,    2, 2018, 2018, 2018])

In [45]:
print(b)
print(b % 2 == 0)

[2 3 4 4 2]
[ True False  True  True  True]


In [46]:
b[b % 2 == 0] = 0

In [47]:
b

array([0, 3, 0, 0, 0])

### Multi-dimensional arrays
* define them using nested lists
* see the shape using `.shape`
* change shape/dimension using `.reshape(shape)`

### Creating 2-dimensional arrays (matrices)
* Example, black-and-white images are 2-dimensional arrays of pixels, where each element is an intensity between 0 and 256 (black is 0, white is 256).

In [48]:
a2 = np.array([[1,2,3],[2,3,4],[3,4,5],[4,5,6]])

In [49]:
a2

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [50]:
a2.shape

(4, 3)

In [51]:
a2.reshape(3,4)

array([[1, 2, 3, 2],
       [3, 4, 3, 4],
       [5, 4, 5, 6]])

In [52]:
a2.reshape(a2.size)

array([1, 2, 3, 2, 3, 4, 3, 4, 5, 4, 5, 6])

### Selecting rows and columns
* `a[i,j]` selects the element in the ith row and jth column (0-indexed!)
* `a[:,j]` selects the jth column.
* `a[i,:]` selects the ith column.

In [53]:
a2

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [54]:
a2[0,2]

3

In [55]:
a2[:,2]

array([3, 4, 5, 6])

In [56]:
a2[2,:]

array([3, 4, 5])

### Change elements using boolean arrays

In [57]:
a2[a2 % 2 == 0] = 0

In [58]:
a2

array([[1, 0, 3],
       [0, 3, 0],
       [3, 0, 5],
       [0, 5, 0]])

### 3 dimensional arrays
* Example, color pictures are 3 dimensional arrays: a triplet of 2D arrays (one for red intensities, one for green intensities, one for blue intensities).

In [59]:
a3 = np.array([
    [[1,2],[2,3],[3,4]],
    [[1,2],[2,3],[3,4]],
    [[1,2],[2,3],[3,4]]
])

In [60]:
a3

array([[[1, 2],
        [2, 3],
        [3, 4]],

       [[1, 2],
        [2, 3],
        [3, 4]],

       [[1, 2],
        [2, 3],
        [3, 4]]])

In [61]:
a3.shape

(3, 3, 2)

In [62]:
a3.reshape(a3.size)

array([1, 2, 2, 3, 3, 4, 1, 2, 2, 3, 3, 4, 1, 2, 2, 3, 3, 4])

In [63]:
a3[0,:,:]

array([[1, 2],
       [2, 3],
       [3, 4]])

In [64]:
a3[:,0,:]

array([[1, 2],
       [1, 2],
       [1, 2]])

In [65]:
a3[:,:,0]

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])